
name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_ANDROID_ARCH: armeabi-v7a

    steps:
      - name: Obter o código
        uses: actions/checkout@v4

      - name: Compilar o aplicativo
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Guardar o APK
        uses: actions/upload-artifact@v4
        with:
          name: meuprimeiroapp-apk
          path: ${{ steps.buildozer.outputs.filename }}
