
name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Obter o código
        uses: actions/checkout@v4

      - name: Preparar Python e Java
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          python -m pip install buildozer cython==0.29.36

      - name: Compilar APK
        run: |
          yes | buildozer android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: meuprimeiroapp-apk
          path: bin/*.apk
          if-no-files-found: error
